######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 4 22:30:26 2011
######################################################################

TEMPLATE = app
QT += core gui xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += freedesktopmime.h mainwindow.h qdesktopview.h
FORMS += mainwindow.ui
SOURCES += freedesktopmime.cpp main.cpp mainwindow.cpp qdesktopview.cpp
RESOURCES += resource.qrc
