#ifndef QWINDOWSCREEN_GLOBAL_H
#define QWINDOWSCREEN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QWINDOWSCREEN_LIBRARY)
#  define QWINDOWSCREENSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QWINDOWSCREENSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QWINDOWSCREEN_GLOBAL_H
