Document: eggwm
Title: Debian eggwm Manual
Author: <insert document author here>
Abstract: This manual describes what eggwm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eggwm/eggwm.sgml.gz

Format: postscript
Files: /usr/share/doc/eggwm/eggwm.ps.gz

Format: text
Files: /usr/share/doc/eggwm/eggwm.text.gz

Format: HTML
Index: /usr/share/doc/eggwm/html/index.html
Files: /usr/share/doc/eggwm/html/*.html
