TEMPLATE = app
CONFIG += qt x11 thread console
TARGET = conf

DEFINES += X11_INC='"$$QMAKE_INCDIR_X11"'
DEFINES += X11_LIBDIR='"$$QMAKE_LIBDIR_X11"'
DEFINES += X11_LIB='"$$QMAKE_LIBS_X11"'
DEFINES += CC='"$$QMAKE_CC"'
DEFINES += CXX='"$$QMAKE_CXX"'

SOURCES += conf.cpp
