######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 14 23:36:06 2011
######################################################################
QT += core gui declarative
include(conf.pri)

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp 

RESOURCES += \
    resource.qrc
